FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY frontend /app/frontend

WORKDIR /app/frontend

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]